config/routes.rb
BootstrapStarter::Application.routes.draw do


	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'},
											 :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

		namespace :admin do
      resources :page_contents
      resources :users
      resources :banks
      resources :api_versions, :except => [:show] do
        resources :api_methods, :except => [:index]
      end
		end

    # api
    match '/api', to: 'api#index', as: :api, via: :get
    namespace :api do
      match '/v1', to: 'v1#index', as: :v1, via: :get
      match '/v1/documentation(/:method)', to: 'v1#documentation', as: :v1_documentation, via: :get

      match "/v1/nbg_currencies" => "v1#nbg_currencies", as: 'v1_nbg_currencies', :via => :get, :defaults => { :format => 'json' }
      match "/v1/nbg_rates" => "v1#nbg_rates", as: 'v1_nbg_rates', :via => :get, :defaults => { :format => 'json' }

      match "/v1/commercial_banks" => "v1#commercial_banks", as: 'v1_commercial_banks', :via => :get, :defaults => { :format => 'json' }
      match "/v1/commercial_banks_with_currency" => "v1#commercial_banks_with_currency", as: 'v1_commercial_banks_with_currency', :via => :get, :defaults => { :format => 'json' }
      match "/v1/commercial_bank_rates" => "v1#commercial_bank_rates", as: 'v1_commercial_bank_rates', :via => :get, :defaults => { :format => 'json' }

      match "/v1/calculator" => "v1#calculator", as: 'v1_calculator', :via => :get, :defaults => { :format => 'json' }
      match "/v1/errors" => "v1#errors", as: 'v1_errors', :via => :get, :defaults => { :format => 'json' }

    end

    # root pages
    match "about" => "root#about", as: 'about', :via => :get
    match "share_test" => "root#share_test", as: 'share_test', :via => :get
    match "story1" => "root#story1", as: 'story1', :via => :get
    match "story2" => "root#story2", as: 'story2', :via => :get
    match "data_download" => "root#data_download", as: 'data_download', :via => :get, :defaults => { :format => 'csv' }

		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/models/api_method.rb
class ApiMethod < ActiveRecord::Base
  translates :title, :content

  belongs_to :api_version

  has_many :api_method_translations, :dependent => :destroy
  accepts_nested_attributes_for :api_method_translations
  attr_accessible :permalink, :public, :public_at, :api_method_translations_attributes
  attr_accessible :api_version_id, :permalink, :public, :public_at, :sort_order
  
  validates :api_version_id, :permalink, :presence => true
  validates_uniqueness_of :permalink, scope: :api_version_id

  #############################
  # Callbacks
  before_save :set_public_at

  # if public and public at not exist, set it
  # else, make nil
  def set_public_at
    if self.public? && self.public_at.nil?
      self.public_at = Time.now.to_date
    elsif !self.public?
      self.public_at = nil
    end
  end

  #############################

  def self.is_public
    where(public: true)
  end

  def self.sorted
    with_translations(I18n.locale).order('api_methods.sort_order asc, api_method_translations.title asc')
  end

  def self.by_permalink(api_version_id, permalink)
    where(permalink: permalink, api_version_id: api_version_id).first
  end


end

app/controllers/admin/api_methods_controller.rb
class Admin::ApiMethodsController < ApplicationController
  before_filter :authenticate_user!
  before_filter do |controller_instance|
    controller_instance.send(:valid_role?, User::ROLES[:admin])
  end
  before_filter :load_admin_assets
  before_filter :load_api_version

  # GET /api_methods/1
  # GET /api_methods/1.json
  def show
    @api_method = ApiMethod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @api_method }
    end
  end

  # GET /api_methods/new
  # GET /api_methods/new.json
  def new
    @api_method = ApiMethod.new

    # create the translation object for however many locales there are
    # so the form will properly create all of the nested form fields
    I18n.available_locales.each do |locale|
      @api_method.api_method_translations.build(:locale => locale.to_s)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @api_method }
    end
  end

  # GET /api_methods/1/edit
  def edit
    @api_method = ApiMethod.find(params[:id])
  end

  # POST /api_methods
  # POST /api_methods.json
  def create
    @api_method = ApiMethod.new(params[:api_method])

    add_missing_translation_content(@api_method.api_method_translations)

    respond_to do |format|
      if @api_method.save
        format.html { redirect_to admin_api_version_api_method_path(@api_version, @api_method), notice: t('app.msgs.success_created', :obj => t('activerecord.models.api_method')) }
        format.json { render json: @api_method, status: :created, location: @api_method }
      else
        format.html { render action: "new" }
        format.json { render json: @api_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /api_methods/1
  # PUT /api_methods/1.json
  def update
    @api_method = ApiMethod.find(params[:id])

    @api_method.assign_attributes(params[:api_method])

    add_missing_translation_content(@api_method.api_method_translations)

    respond_to do |format|
      if @api_method.save
        format.html { redirect_to admin_api_version_api_method_path(@api_version, @api_method), notice: t('app.msgs.success_updated', :obj => t('activerecord.models.api_method')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @api_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_methods/1
  # DELETE /api_methods/1.json
  def destroy
    @api_method = ApiMethod.find(params[:id])
    @api_method.destroy

    respond_to do |format|
      format.html { redirect_to admin_api_versions_url }
      format.json { head :no_content }
    end
  end

private

  def load_api_version
    @api_version = ApiVersion.find(params[:api_version_id])

    if @api_version.nil?
      redirect_to admin_api_path, :notice => t('app.msgs.does_not_exist')
    end
  end 

end

app/helpers/api_methods_helper.rb
module ApiMethodsHelper

  # if public_at and updated_at are same dates, only show public_at, else both
  def format_api_method_dates(api_method)
    model_class = ApiMethod

    text = ''
    if api_method.public_at.present? && api_method.updated_at.present?
      if api_method.public_at == api_method.updated_at.to_date
        text << "<span>"
        text << model_class.human_attribute_name(:public_at)
        text << ": "
        text << I18n.l(api_method.public_at, format: :day_first)
        text << "</span>"
      else
        text << "<span>"
        text << model_class.human_attribute_name(:public_at)
        text << ": "
        text << I18n.l(api_method.public_at, format: :day_first)
        text << "</span>"
        text << "<span>"
        text << model_class.human_attribute_name(:updated_at)
        text << ": "
        text << I18n.l(api_method.updated_at.to_date, format: :day_first)
        text << "</span>"
      end
    end
    return text.html_safe
  end
end

app/views/admin/api_methods/_form.html.erb
<%= tinymce_assets %>
<%= tinymce :advanced %>

<%= semantic_form_for([:admin, @api_version, @api_method]) do |f| %>
  <%= f.error_messages %>

  <% create_sorted_translation_objects(@api_method.api_method_translations).each do |trans| %>
    <%= f.fields_for :api_method_translations, trans do |translation| %>

      <div id="form-<%= trans.locale %>" class="multilanguage_nested">
        <h3><%= t("app.language.#{trans.locale}") %></h3>

        <%= translation.input :title %>
        <%= translation.input :content, :as => :text, rows: 10, :input_html => { class: 'tinymce' } %>
        <%= translation.hidden_field :locale , :value => trans.locale %>
      </div>

    <% end %>
  <% end %>

  <%= f.inputs do %>
    <%= f.input :permalink, :input_html => {:size =>35} %>
    <%= f.input :sort_order, as: :number, min: 1, step: 5 %>
    <%= f.input :public, as: :radio %>
    <%= f.input :api_version_id, as: :hidden, label: false, input_html: {value: params[:api_version_id]} %>
  <% end %>

  <div class="form-group">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= f.submit nil, :class => 'btn btn-warning', :type => :reset, :value => t('helpers.links.reset'), :name => :reset %>
    <%= link_to t('helpers.links.cancel'), admin_api_versions_path, :class => 'btn btn-sm btn-warning' %>
  </div>
<% end %>

app/views/admin/api_methods/edit.html.erb
<%- model_class = ApiMethod -%>
<% title t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %>
<div class="form-group form-group-admin-buttons">
  <%= link_to t('helpers.links.list'), admin_api_versions_path,
  :class => 'btn btn-default' %>
  <%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/api_methods/new.html.erb
<%- model_class = ApiMethod -%>
<% title t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %>
<div class="form-group form-group-admin-buttons">
  <%= link_to t('helpers.links.list'), admin_api_versions_path,
  :class => 'btn btn-default' %>
  <%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/api_methods/show.html.erb
<%- model_class = ApiMethod -%>
<% title t '.title', :default => model_class.model_name.human %>


<div class="form-group form-group-admin-buttons">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_api_versions_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_api_version_api_method_path(@api_version, @api_method), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_api_version_api_method_path(@api_version, @api_method),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm")) },
              :class => 'btn btn-danger' %>
  <%= link_to t('helpers.links.admin'), admin_path, :class => 'btn btn-default' %>
</div>

<p><strong><%= model_class.human_attribute_name(:title) %>:</strong>
<%= @api_method.title %></p>

<p><strong><%= model_class.human_attribute_name(:permalink) %>:</strong>
<%= @api_method.permalink %></p>

<p><strong><%= model_class.human_attribute_name(:sort_order) %>:</strong>
<%= @api_method.sort_order %></p>

<p><strong><%= model_class.human_attribute_name(:public) %>:</strong>
<%= @api_method.public %></p>

<p><strong><%= model_class.human_attribute_name(:public_at) %>:</strong>
<%= l @api_method.public_at, format: :day_first if @api_method.public_at %></p>

<p><strong><%= model_class.human_attribute_name(:content) %>:</strong></p>
<div class="tinymce_format">
  <%= simple_format_no_tags(@api_method.content, {}, {sanitize: false}) %>
</div>