config/routes.rb
BootstrapStarter::Application.routes.draw do


	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'},
											 :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

		namespace :admin do
      resources :page_contents
      resources :users
      resources :banks
      resources :api_versions, :except => [:show] do
        resources :api_methods, :except => [:index]
      end
		end

    # api
    match '/api', to: 'api#index', as: :api, via: :get
    namespace :api do
      match '/v1', to: 'v1#index', as: :v1, via: :get
      match '/v1/documentation(/:method)', to: 'v1#documentation', as: :v1_documentation, via: :get

      match "/v1/nbg_currencies" => "v1#nbg_currencies", as: 'v1_nbg_currencies', :via => :get, :defaults => { :format => 'json' }
      match "/v1/nbg_rates" => "v1#nbg_rates", as: 'v1_nbg_rates', :via => :get, :defaults => { :format => 'json' }

      match "/v1/commercial_banks" => "v1#commercial_banks", as: 'v1_commercial_banks', :via => :get, :defaults => { :format => 'json' }
      match "/v1/commercial_banks_with_currency" => "v1#commercial_banks_with_currency", as: 'v1_commercial_banks_with_currency', :via => :get, :defaults => { :format => 'json' }
      match "/v1/commercial_bank_rates" => "v1#commercial_bank_rates", as: 'v1_commercial_bank_rates', :via => :get, :defaults => { :format => 'json' }

      match "/v1/calculator" => "v1#calculator", as: 'v1_calculator', :via => :get, :defaults => { :format => 'json' }
      match "/v1/errors" => "v1#errors", as: 'v1_errors', :via => :get, :defaults => { :format => 'json' }

    end

    # root pages
    match "about" => "root#about", as: 'about', :via => :get
    match "share_test" => "root#share_test", as: 'share_test', :via => :get
    match "story1" => "root#story1", as: 'story1', :via => :get
    match "story2" => "root#story2", as: 'story2', :via => :get
    match "data_download" => "root#data_download", as: 'data_download', :via => :get, :defaults => { :format => 'csv' }

		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/models/api_version.rb
class ApiVersion < ActiveRecord::Base
  translates :title

  has_many :api_methods, dependent: :destroy
  has_many :api_version_translations, :dependent => :destroy
  accepts_nested_attributes_for :api_version_translations
  attr_accessible :permalink, :public, :public_at, :api_version_translations_attributes
  
  validates :permalink, :presence => true

  #############################
  # Callbacks
  before_save :set_public_at

  # if public and public at not exist, set it
  # else, make nil
  def set_public_at
    if self.public? && self.public_at.nil?
      self.public_at = Time.now.to_date
    elsif !self.public?
      self.public_at = nil
    end
  end

  #############################

  def self.is_public
    where(public: true)
  end

  def self.sorted
    with_translations(I18n.locale).order('api_versions.public_at asc, api_version_translations.title asc')
  end

  def self.by_permalink(permalink)
    find_by_permalink(permalink)
  end
end

app/controllers/admin/api_versions_controller.rb
class Admin::ApiVersionsController < ApplicationController
  before_filter :authenticate_user!
  before_filter do |controller_instance|
    controller_instance.send(:valid_role?, User::ROLES[:admin])
  end
  before_filter :load_admin_assets

  # GET /api_versions
  # GET /api_versions.json
  def index
    @api_versions = ApiVersion.sorted

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @api_versions }
    end
  end

  # GET /api_versions/new
  # GET /api_versions/new.json
  def new
    @api_version = ApiVersion.new

    # create the translation object for however many locales there are
    # so the form will properly create all of the nested form fields
    I18n.available_locales.each do |locale|
      @api_version.api_version_translations.build(:locale => locale.to_s)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @api_version }
    end
  end

  # GET /api_versions/1/edit
  def edit
    @api_version = ApiVersion.find(params[:id])
  end

  # POST /api_versions
  # POST /api_versions.json
  def create
    @api_version = ApiVersion.new(params[:api_version])

    add_missing_translation_content(@api_version.api_version_translations)

    respond_to do |format|
      if @api_version.save
        format.html { redirect_to admin_api_versions_path, notice: t('app.msgs.success_created', :obj => t('activerecord.models.api_version')) }
        format.json { render json: @api_version, status: :created, location: @api_version }
      else
        format.html { render action: "new" }
        format.json { render json: @api_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /api_versions/1
  # PUT /api_versions/1.json
  def update
    @api_version = ApiVersion.find(params[:id])

    @api_version.assign_attributes(params[:api_version])

    add_missing_translation_content(@api_version.api_version_translations)

    respond_to do |format|
      if @api_version.save
        format.html { redirect_to admin_api_versions_path, notice: t('app.msgs.success_updated', :obj => t('activerecord.models.api_version')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @api_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_versions/1
  # DELETE /api_versions/1.json
  def destroy
    @api_version = ApiVersion.find(params[:id])
    @api_version.destroy

    respond_to do |format|
      format.html { redirect_to admin_api_versions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/api_versions_helper.rb
module ApiVersionsHelper
end

app/views/admin/api_versions/_form.html.erb
<%= semantic_form_for([:admin,@api_version]) do |f| %>
  <%= f.error_messages %>

  <% create_sorted_translation_objects(@api_version.api_version_translations).each do |trans| %>
    <%= f.fields_for :api_version_translations, trans do |translation| %>

      <div id="form-<%= trans.locale %>" class="multilanguage_nested">
        <h3><%= t("app.language.#{trans.locale}") %></h3>

        <%= translation.input :title %>
        <%= translation.hidden_field :locale , :value => trans.locale %>
      </div>

    <% end %>
  <% end %>

  <%= f.inputs do %>
    <%= f.input :permalink, :input_html => {:size =>35} %>
    <%= f.input :public, as: :radio %>
  <% end %>

  <div class="form-group">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= f.submit nil, :class => 'btn btn-warning', :type => :reset, :value => t('helpers.links.reset'), :name => :reset %>
    <%= link_to t('helpers.links.cancel'), admin_api_versions_path, :class => 'btn btn-sm btn-warning' %>
  </div>
<% end %>

app/views/admin/api_versions/edit.html.erb
<%- model_class = ApiVersion -%>
<% title t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %>
<div class="form-group form-group-admin-buttons">
  <%= link_to t('helpers.links.list'), admin_api_versions_path,
  :class => 'btn btn-default' %>
  <%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/api_versions/index.html.erb
<%- model_class = ApiVersion -%>
<% title t '.title', :default => model_class.model_name.human.pluralize %>

<div class="form-group form-group-admin-buttons">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_admin_api_version_path,
              :class => 'btn btn-primary' %>
  <%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<table class="table table-striped display">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:permalink) %></th>
      <th><%= model_class.human_attribute_name(:public) %></th>
      <th><%= model_class.human_attribute_name(:methods) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @api_versions.each do |api_version| %>
      <tr>
        <td><%= link_to api_version.title, admin_api_version_path(api_version) %></td>
        <td><%= api_version.permalink %></td>
        <td><%= format_public_status(api_version.public) %></td>
        <td>
          <%= link_to t('.new', :default => t("helpers.links.new")),
              new_admin_api_version_api_method_path(api_version),
              :class => 'btn btn-primary btn-xs' %>
          <% if api_version.api_methods.present? %>
            <ul>
              <% api_version.api_methods.sorted.each do |method| %>
                <li>
                  <%= link_to method.title, admin_api_version_api_method_path(api_version, method) %>
                  <%= format_public_status(method.public, true) %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </td>
        <td>
          <%= link_to t('app.buttons.edit'),
                      edit_admin_api_version_path(api_version), :class => 'btn btn-xs btn-default' %>
          <%= link_to t('app.buttons.delete'),
                      admin_api_version_path(api_version),
                      :method => :delete,
                      :data => { :confirm => I18n.t("helpers.links.confirm") },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/api_versions/new.html.erb
<%- model_class = ApiVersion -%>
<% title t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %>
<div class="form-group form-group-admin-buttons">
  <%= link_to t('helpers.links.list'), admin_api_versions_path,
  :class => 'btn btn-default' %>
  <%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/api_versions/show.html.erb
<%- model_class = ApiVersion -%>
<% title t '.title', :default => model_class.model_name.human %>


<div class="form-group form-group-admin-buttons">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_api_versions_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_api_version_path(@api_version), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_api_version_path(@api_version),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm")) },
              :class => 'btn btn-danger' %>
  <%= link_to t('helpers.links.admin'), admin_path, :class => 'btn btn-default' %>
</div>

<p><strong><%= model_class.human_attribute_name(:title) %>:</strong>
<%= @api_version.title %></p>

<p><strong><%= model_class.human_attribute_name(:permalink) %>:</strong>
<%= @api_version.permalink %></p>

<p><strong><%= model_class.human_attribute_name(:public) %>:</strong>
<%= @api_version.public %></p>

<p><strong><%= model_class.human_attribute_name(:public_at) %>:</strong>
<%= l @api_version.public_at, format: :day_first if @api_version.public_at %></p>