config/routes.rb
BootstrapStarter::Application.routes.draw do


	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'},
											 :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

		namespace :admin do
      resources :page_contents
      resources :users
      resources :banks
      resources :api_versions, :except => [:show] do
        resources :api_methods, :except => [:index]
      end
		end

    # api
    match '/api', to: 'api#index', as: :api, via: :get
    namespace :api do
      match '/v1', to: 'v1#index', as: :v1, via: :get
      match '/v1/documentation(/:method)', to: 'v1#documentation', as: :v1_documentation, via: :get

      match "/v1/nbg_currencies" => "v1#nbg_currencies", as: 'v1_nbg_currencies', :via => :get, :defaults => { :format => 'json' }
      match "/v1/nbg_rates" => "v1#nbg_rates", as: 'v1_nbg_rates', :via => :get, :defaults => { :format => 'json' }

      match "/v1/commercial_banks" => "v1#commercial_banks", as: 'v1_commercial_banks', :via => :get, :defaults => { :format => 'json' }
      match "/v1/commercial_banks_with_currency" => "v1#commercial_banks_with_currency", as: 'v1_commercial_banks_with_currency', :via => :get, :defaults => { :format => 'json' }
      match "/v1/commercial_bank_rates" => "v1#commercial_bank_rates", as: 'v1_commercial_bank_rates', :via => :get, :defaults => { :format => 'json' }

      match "/v1/calculator" => "v1#calculator", as: 'v1_calculator', :via => :get, :defaults => { :format => 'json' }
      match "/v1/errors" => "v1#errors", as: 'v1_errors', :via => :get, :defaults => { :format => 'json' }

    end

    # root pages
    match "about" => "root#about", as: 'about', :via => :get
    match "share_test" => "root#share_test", as: 'share_test', :via => :get
    match "story1" => "root#story1", as: 'story1', :via => :get
    match "story2" => "root#story2", as: 'story2', :via => :get
    match "data_download" => "root#data_download", as: 'data_download', :via => :get, :defaults => { :format => 'csv' }

		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/models/page_content.rb
class PageContent < ActiveRecord::Base
  translates :title, :content

  has_many :page_content_translations, :dependent => :destroy
  accepts_nested_attributes_for :page_content_translations
  attr_accessible :id, :name, :page_content_translations_attributes
  
  validates :name, :presence => true

  def self.by_name(name)
    with_translations(I18n.locale).find_by_name(name)
  end

end

app/controllers/admin/page_contents_controller.rb
class Admin::PageContentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter do |controller_instance|
    controller_instance.send(:valid_role?, User::ROLES[:admin])
  end
  before_filter :load_admin_assets

  # GET /pages
  # GET /pages.json
  def index
    @page_contents = PageContent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @page_contents }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page_content = PageContent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page_content }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page_content = PageContent.new

    # create the translation object for however many locales there are
    # so the form will properly create all of the nested form fields
    I18n.available_locales.each do |locale|
      @page_content.page_content_translations.build(:locale => locale.to_s)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page_content }
    end
  end

  # GET /pages/1/edit
  def edit
    @page_content = PageContent.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page_content = PageContent.new(params[:page_content])

    add_missing_translation_content(@page_content.page_content_translations)

    respond_to do |format|
      if @page_content.save
        format.html { redirect_to admin_page_content_path(@page_content), notice: t('app.msgs.success_created', :obj => t('activerecord.models.page_content')) }
        format.json { render json: @page_content, status: :created, location: @page_content }
      else
        format.html { render action: "new" }
        format.json { render json: @page_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page_content = PageContent.find(params[:id])

    @page_content.assign_attributes(params[:page_content])

    add_missing_translation_content(@page_content.page_content_translations)

    respond_to do |format|
      if @page_content.save
        format.html { redirect_to admin_page_content_path(@page_content), notice: t('app.msgs.success_updated', :obj => t('activerecord.models.page_content')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page_content = PageContent.find(params[:id])
    @page_content.destroy

    respond_to do |format|
      format.html { redirect_to admin_page_contents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/page_contents_helper.rb
module PageContentsHelper
end

app/views/admin/page_contents/_form.html.erb
<%= tinymce_assets %>
<%= tinymce %>

<%= semantic_form_for([:admin,@page_content]) do |f| %>
  <%= f.error_messages %>

  <%= f.inputs do %>
    <%= f.input :name, :input_html => {:size =>35} %>
  <% end %>

  <% create_sorted_translation_objects(@page_content.page_content_translations).each do |trans| %>
    <%= f.fields_for :page_content_translations, trans do |translation| %>

      <div id="form-<%= trans.locale %>" class="multilanguage_nested">
        <h3><%= t("app.language.#{trans.locale}") %></h3>

        <%= translation.input :title %>
        <%= translation.input :content, :as => :text, rows: 10, :input_html => { class: 'tinymce' } %>
        <%= translation.hidden_field :locale , :value => trans.locale %>
      </div>

    <% end %>
  <% end %>


  <div class="form-group">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= f.submit nil, :class => 'btn btn-warning', :type => :reset, :value => t('helpers.links.reset'), :name => :reset %>
    <%= link_to t('helpers.links.cancel'), admin_page_contents_path, :class => 'btn btn-sm btn-warning' %>
  </div>
<% end %>

app/views/admin/page_contents/edit.html.erb
<%- model_class = PageContent -%>
<% title t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %>

<div class="form-group form-group-admin-buttons">
  <%= link_to t('helpers.links.list'), admin_page_contents_path,
  :class => 'btn btn-default' %>
  <%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/page_contents/index.html.erb
<%- model_class = PageContent -%>
<%- model_class_t = PageContentTranslation -%>
<% title t '.title', :default => model_class.model_name.human.pluralize %>

<div class="form-group form-group-admin-buttons">
<%= link_to t('helpers.links.new'),
            new_admin_page_content_path,
            :class => 'btn btn-primary' %>
<%= link_to t('helpers.links.admin'), admin_path,
:class => 'btn btn-default' %>
</div>

<table class="table table-striped display">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class_t.human_attribute_name(:title) %></th>
      <th><%= t('helpers.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @page_contents.each do |page_content| %>
      <tr>
        <td>
          <%= link_to page_content.name, admin_page_content_path(page_content) %>
        </td>
        <td>
          <%= link_to page_content.title, admin_page_content_path(page_content) %>
        </td>
        <td>
          <%= link_to(I18n.t("helpers.links.edit"),
                            edit_admin_page_content_path(page_content, :locale => I18n.locale), :class => 'btn btn-default btn-xs') %>

          <%= link_to(I18n.t("helpers.links.destroy"),
                            admin_page_content_path(page_content, :locale => I18n.locale),
                            :method => :delete,
                            :data => { :confirm => I18n.t("helpers.links.confirm") },
                            :class => 'btn btn-xs btn-danger') %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/page_contents/new.html.erb
<%- model_class = PageContent -%>
<% title t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %>

<div class="form-group form-group-admin-buttons">
  <%= link_to t('helpers.links.list'), admin_page_contents_path,
  :class => 'btn btn-default' %>
  <%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<%= render :partial => 'form' %>

app/views/admin/page_contents/show.html.erb
<%- model_class = PageContent -%>
<%- model_class_t = PageContentTranslation -%>
<% title t '.title', :default => model_class.model_name.human %>

<div class="form-group form-group-admin-buttons">
  <%= link_to t('helpers.links.list'),
              admin_page_contents_path, :class => 'btn btn-default'  %>
  <%= link_to t('helpers.links.edit'),
              edit_admin_page_content_path(@page_content), :class => 'btn btn-default' %>
  <%= link_to t('helpers.links.delete'),
              admin_page_content_path(@page_content),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm")) },
              :class => 'btn btn-danger' %>
  <%= link_to t('helpers.links.admin'), admin_path,
  :class => 'btn btn-default' %>
</div>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong>
  <%= @page_content.name %>
</p>
<p>
  <strong><%= model_class_t.human_attribute_name(:title) %>:</strong>
  <%= @page_content.title %>
</p>
<p>
  <strong><%= model_class_t.human_attribute_name(:content) %>:</strong>
</p>
<div class="tinymce_format">
  <%= simple_format_no_tags(@page_content.content, {}, {sanitize: false}) %>
</div>