config/routes.rb
BootstrapStarter::Application.routes.draw do


	#--------------------------------
	# all resources should be within the scope block below
	#--------------------------------
	scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do

		match '/admin', :to => 'admin#index', :as => :admin, :via => :get
		devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'},
											 :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

		namespace :admin do
      resources :page_contents
      resources :users
      resources :banks
      resources :api_versions, :except => [:show] do
        resources :api_methods, :except => [:index]
      end
		end

    # api
    match '/api', to: 'api#index', as: :api, via: :get
    namespace :api do
      match '/v1', to: 'v1#index', as: :v1, via: :get
      match '/v1/documentation(/:method)', to: 'v1#documentation', as: :v1_documentation, via: :get

      match "/v1/nbg_currencies" => "v1#nbg_currencies", as: 'v1_nbg_currencies', :via => :get, :defaults => { :format => 'json' }
      match "/v1/nbg_rates" => "v1#nbg_rates", as: 'v1_nbg_rates', :via => :get, :defaults => { :format => 'json' }

      match "/v1/commercial_banks" => "v1#commercial_banks", as: 'v1_commercial_banks', :via => :get, :defaults => { :format => 'json' }
      match "/v1/commercial_banks_with_currency" => "v1#commercial_banks_with_currency", as: 'v1_commercial_banks_with_currency', :via => :get, :defaults => { :format => 'json' }
      match "/v1/commercial_bank_rates" => "v1#commercial_bank_rates", as: 'v1_commercial_bank_rates', :via => :get, :defaults => { :format => 'json' }

      match "/v1/calculator" => "v1#calculator", as: 'v1_calculator', :via => :get, :defaults => { :format => 'json' }
      match "/v1/errors" => "v1#errors", as: 'v1_errors', :via => :get, :defaults => { :format => 'json' }

    end

    # root pages
    match "about" => "root#about", as: 'about', :via => :get
    match "share_test" => "root#share_test", as: 'share_test', :via => :get
    match "story1" => "root#story1", as: 'story1', :via => :get
    match "story2" => "root#story2", as: 'story2', :via => :get
    match "data_download" => "root#data_download", as: 'data_download', :via => :get, :defaults => { :format => 'csv' }

		root :to => 'root#index'
	  match "*path", :to => redirect("/#{I18n.default_locale}") # handles /en/fake/path/whatever
	end

	match '', :to => redirect("/#{I18n.default_locale}") # handles /
	match '*path', :to => redirect("/#{I18n.default_locale}/%{path}") # handles /not-a-locale/anything

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= content_for?(:title) ? "#{yield(:title)} | #{t('app.common.app_name')}" : t('app.common.app_name') %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= content_for?(:description) ? "#{yield(:description)}" : t('app.common.description') %>">
    <meta property="og:title" content="<%= content_for?(:title) ? "#{yield(:title)} | #{t('app.common.app_name')}" : t('app.common.app_name') %>">
    <meta property="og:description" content="<%= content_for?(:description) ? "#{yield(:description)}" : t('app.common.description') %>">
    <meta property="og:type" content="non_profit">
    <meta property="og:url" content="<%= current_url %>">
    <meta property="og:image" content="<%= full_url('/assets/fb_'+I18n.locale.to_s+'.jpg') %>">
    <meta property="og:site_name" content="<%= t('app.common.app_name') %>" >

    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#ffc539">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#ffc539">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <%= csrf_meta_tags %>
	  <%= include_gon %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag  *(@css.present? ? ["application",@css].flatten : ["application"]), :media => "all" %>
		<!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
	  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="wrapper">

      <div class="container">
       <div class="header">
        <div class="box">
          <div class="logo">
            <%= link_to image_tag("/assets/svg/logo_#{I18n.locale}.svg", :alt => t('app.common.app_name')), root_path %>
          </div>
          <div class="menu-toggle"><img src="/assets/svg/menu_cg.svg" alt="<%= t('app.common.nav_toggle') %>"></div>
          <div class="right des">
            <% if user_signed_in? %>
              <% if current_user.role?(User::ROLES[:admin]) %>
                <div>
                 <%= link_to t('helpers.links.admin'), admin_path %>
                </div>
                <div class="sep">|</div>
              <% end %>
              <div>
               <%= link_to t('helpers.links.sign_out'), destroy_user_session_path, :method => :delete %>
              </div>
              <div class="sep">|</div>
            <% end %>
            <div><%= link_to t("app.common.about"), about_path %></div>
            <div class="sep">|</div>
            <div class="lang-switch">
                      <% I18n.available_locales.each do |locale| %>
                         <% if locale != I18n.locale %>
                            <%= link_to t("app.language.#{locale}"), {:locale => locale}, lang: locale, url: root_path(:locale => locale), id:"lang-link" %>
                         <% end %>
                      <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="line"></div>
      <div class="content">
        <div class="sub-line"></div>
        <div class="tabs">
          <div class="tab" data-id="commercial_banks"><%= link_to t("root.tab3"), root_path(:anchor=>'p=commercial_banks') %></div>
          <div class="tab" data-id="national_bank"><%= link_to t("root.tab2"), root_path(:anchor=>'p=national_bank') %></div>
          <div class="tab" data-id="calculator"><%= link_to t("root.tab1"), root_path(:anchor=>'p=calculator') %></div>
          <div class="tab<%= @tab == 'api' ? ' active' : '' %>"><%= link_to t("app.common.api"), api_path %></div>
          <div class="tab mob"><%= link_to t("app.common.about"), about_path %></div>
          <div class="tab mob"><% I18n.available_locales.each do |locale| %>
                         <% if locale != I18n.locale %>
                            <%= link_to t("app.language.#{locale}"), {:locale => locale}, lang: locale, url: root_path(:locale => locale), id:"lang-link" %>
                         <% end %>
                      <% end %>
          </div>
        </div>

        <% if content_for?(:title) && !(params[:controller] == 'root' && params[:action] == 'index') %>
          <div class="page-header">
            <h1><%= yield(:title) %></h1>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
    <div class="footer">
      <div class="box">
        <div class="share">
          <div><%= t('app.common.share') %></div>
          <div class="addthis_sharing_toolbox"></div>
        </div>
        <div class="last-update"><%= t('app.common.last_update') %><span><%= "#{I18n.l @last_scrapped_at, format: :long}" %></span></div>
        <div class='powered-by'>
          <%= link_to(image_tag("svg/js.svg"), "http://www.jumpstart.ge", :target => "_blank",
              :title => t('app.common.js_link_title') ) %>
        </div>
      </div>
    </div>
  </div>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag  *(@js.present? ? ["application", @js].flatten : ["application"]), :media => "all" %>
		<script type="text/javascript">
			I18n.defaultLocale = "<%= I18n.default_locale %>";
			I18n.locale = "<%= I18n.locale %>";
		</script>
    <% if I18n.locale == :ka %>
      <%= javascript_include_tag "datepicker-ka" %>
    <% end %>

		<% if Rails.env.production? %>
      <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-55373fab24a51695" async="async"></script>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-12801815-42', 'auto');
        ga('send', 'pageview');

      </script>
		<% end %>

  </body>
</html>

app/views/layouts/unsupported_browser.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? "#{yield(:title)} | #{t('app.common.app_name')}" :
				t('app.common.app_name') %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
    <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>


    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <%= link_to(t('app.common.app_name'), root_path(:locale => I18n.locale),:class=>"navbar-brand font")%>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
						<% I18n.available_locales.each do |locale| %>
							<% if locale != I18n.locale %>
								<li><%= link_to t("app.language.#{locale}"), params.merge(:locale => locale) %></li>
							<% end %>
						<% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

	  <div class="container">
      <div class="row">
         <div class="col-sm-12">

            <div class="page-header">
	            <h1>
								<%= t('.title') %>
							</h1>
						</div>

						<p><%= t('.p1') %></p>
						<p><%= t('.p2') %></p>
						<ul class="standard">
							<li>
								<a href="http://www.google.com/chrome/"><%= t('.chrome') %></a>
							</li>
							<li>
								<a href="http://www.mozilla.org/firefox/new/"><%= t('.firefox') %></a>
							</li>
							<li>
								<a href="http://windows.microsoft.com/en-US/internet-explorer/downloads/ie/"><%= t('.ie') %></a>
							</li>
							<li>
								<a href="http://www.opera.com/download/"><%= t('.opera') %></a>
							</li>
							<li>
								<a href="http://support.apple.com/downloads/#internet"><%= t('.safari') %></a>
							</li>
						</ul>
          <%= yield %>
        </div><!--/span-->
      </div><!--/row-->
    </div> <!-- /container -->


	<% if Rails.env.production? %>
		<!-- google analytics -->
	<% elsif Rails.env.staging? %>
		<!-- google analytics -->
	<% end %>

  </body>
</html>